### ISSUE TITLE
Headings are send in email including [[!+fi.field_1]]

### ISSUE THREAD

**Issue by RobertSK** [Sterc/Formalicious#1]
Hi and thank you for making your great plugin free to use.
Headings are send in email including **[[!+fi.field_1]]**, how to remove **[[!+fi.field_1]]**?

Kind Regards
Robert

**Comment by jenswittmann** [comment]
Hello @RobertSK  i came a acrros with this issue in the last months. Here is a [Forumthread](https://forum.modmore.com/t/placeholder-shown-on-email-tpl/1988) and an answer from @Mark-H (modmore Support):

> I do wonder if that might be FormIt issue? While Formalicious generates the email, I think Formit is supposed to do the actual parsing/removing of unused placeholders...

I think the problem ist that the Heading is used as an input, but the input is missing on sending the form. Because this, the placeholder doens't get replaced by FormIt. The easiest way could be an hidden input: 6d47c86

**Comment by RobertSK** [comment]
Thank you @jenswittmann,
that solved my problem.

**Comment by RobertSK** [comment]
I think this should be added to the title chunk as default.
